# Generated by Django 3.2.16 on 2024-10-08 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0003_rename_county_location_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'default_related_name': 'tours', 'ordering': ('pk',), 'verbose_name': 'тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AddField(
            model_name='tour',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.location', verbose_name='Тур'),
        ),
    ]
